zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: devartis/storm-nimbus:1.0.2
  ports:
    - "3773:3773"
    - "3772:3772"
    - "6627:6627"
    - "49022:22"
  links: 
    - zookeeper:zk
supervisor:
  image: devartis/storm-supervisor:1.0.2
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: devartis/storm-ui:1.0.2
  ports:
    - "8080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
